import { Movie } from './types';

export const CURATED_MOVIES: Movie[] = [
  {
    id: 'midnight-reckoning',
    title: 'Midnight Reckoning',
    year: 2024,
    type: 'movie',
    duration: '2h 05m',
    genres: ['Thriller', 'Noir', 'Action'],
    rating: 9.8,
    isFeatured: true,
    description: 'In a city that never sleeps, one detective must navigate a web of betrayal to clear his name before the clock strikes twelve.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCt39pNrRLf-zmhLg5Ysbya_2njSxd2AU4NNY2AoJGsrUePb2REg6soIMa6pFAULtRZhI5U4QDiOk2ruzH8wHPLac8KW81qTnUhBd2G9QgleRSHkyZhHNSlAmVl6QQUTEP2GE5cuCOvhJu_tVRjW_WHnUkkiDMrZESr6QtaZIMqBPAga_jFMBQ-Iuni9m8z0vDbU1R7gLZZri5CAGDxF7-ZAnTG2pDipPrdZk8JzlnMn0AhPfVcQi9rUg3IgIkUYO1AWviZLxBiOAA',
    bgUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCt39pNrRLf-zmhLg5Ysbya_2njSxd2AU4NNY2AoJGsrUePb2REg6soIMa6pFAULtRZhI5U4QDiOk2ruzH8wHPLac8KW81qTnUhBd2G9QgleRSHkyZhHNSlAmVl6QQUTEP2GE5cuCOvhJu_tVRjW_WHnUkkiDMrZESr6QtaZIMqBPAga_jFMBQ-Iuni9m8z0vDbU1R7gLZZri5CAGDxF7-ZAnTG2pDipPrdZk8JzlnMn0AhPfVcQi9rUg3IgIkUYO1AWviZLxBiOAA'
  },
  {
    id: 'neon-genesis-tokyo',
    title: 'Neon Genesis: Tokyo',
    year: 2024,
    type: 'movie',
    duration: '2h 15m',
    genres: ['Sci-Fi', 'Cyberpunk'],
    rating: 4.9,
    description: 'A rain-slicked cyberpunk street in Tokyo at night, where neon lights of crimson and electric blue cast long, eerie reflections under futuristic corporate shadows.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDdiNLbn8WmswWfztBcCN2UwgmdCyz2xwJB5tRWZGinnoizx_9N-GMIIy9S0KbL_rR6ijqfWk4grqKGjiQVbkEAg-gYy6ZJGu2-2aAyDk1Y8g8235zB8sbsYYMzl0qku-exEQSsZCm9QviVj9IwhxQYIaPvavPaH2Ph02trDPzz2pFrqziQLc0sDX42WEKdE9avxTVuwRWnhEkDzSYbptr39mdiNWuVz2zDhQC_Ut0FhX8pJ4MlX8DgdTR4EkSwImtdsDEuDXRxOuI'
  },
  {
    id: 'the-red-beyond',
    title: 'The Red Beyond',
    year: 2023,
    type: 'movie',
    duration: '1h 58m',
    genres: ['Adventure', 'Sci-Fi'],
    rating: 4.8,
    description: 'An astronaut gazes from a spaceship viewport at a glowing, celestial red nebula structure, confronting the vast, awe-inspiring silence of space.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZCOGAKAC1J3NqjYfTyl58ZVmh1gytgT7TjaqyQEx6OiqQQiieF4KSN2dPud2ohUU6k25oLZKUY_7POL-EqTv-IKeIkoAKETxFyIGYz5Mxi7bh2NxQhGa2_abfncrBGb8xUF41wB4N4hwGkA4oRqEfO1SlIeFkn1_nE4_G2kJqNzTcPXOjVB2krlTIdptgV0T9LMzD-QHtkE2XpFQnXnhH8-hTShqVj3_gwwe9uegzPgwVqoHcaGqbk8V0gklbgfvQjUBKRhCZ0DY'
  },
  {
    id: 'midnight-jazz',
    title: 'Midnight Jazz',
    year: 2022,
    type: 'movie',
    duration: '1h 45m',
    genres: ['Drama', 'Music'],
    rating: 4.6,
    description: 'A vintage spotlight stands dramatically in a smoky jazz club, while a silent piano player conjures melodies in the obsidian twilight shadows.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5nMFSfUeXwh3SISNgIUOzBVd69fASzC5dUYBWTSOvm4-mvCf3xA-Dnee31FhTeth873hAD6BoYc2ndDThvJJrVXIgrcgmKyImtVz-iCX-20Y9VRawL57QtpdgdNYTt8ZQmld_qxzBt1ShufgAsYkrdiEkaJ7gL8NBo9HpCoxGa0wC6RQCF1pY5dRbHObboyebu5LqYZNx9h3twGh6KWjtr270KQGIVZtw8axfnMCjkuvNWXFy5IFzWGxZ5YpCJpY358B74h9itjA'
  },
  {
    id: 'shadow-realm',
    title: 'Shadow Realm',
    year: 2024,
    type: 'movie',
    duration: '2h 10m',
    genres: ['Fantasy', 'Thriller'],
    rating: 4.7,
    description: 'A dark, jagged mountain peak stretches towards a massive blood-red moon, with a solitary fantasy fortress illuminated on a near precipice.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDCDpE9DJrV20Gics1IPtUoquS6G1n03xEJQd-K2bvygrINvcbbEhYCeDQiDIKOsMW-xddUFLFXWWOX9GDJdlyTFtjbAkIiG1hc6U2wA7DyhfVEyaPyhm9JupJDgm_v3wyHWRPSsDLdtJUq16rkPZP2MooBdEt5A1CzwQgXjySLMncfGkWoZdcZtKUXdU2LWPx5kMPLV-YbteQKnGPZjEdfKz-BQhIwfikqAcw4zzdi4-gSiq0O1dNtv0MuoepaTHgzIBQcD-iH_U'
  },
  {
    id: 'the-silent-echo',
    title: 'The Silent Echo',
    year: 2023,
    type: 'movie',
    duration: '2h 02m',
    genres: ['Sci-Fi', 'Arthouse'],
    rating: 4.9,
    description: 'A lone explorer stands on the precipice of a vast golden space rift, surrounded by dark alien sands and silent purple galaxies.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE9JoOebP5aB5BcC486MM6pnio3D8fO-LQUoiG4HVdZurDAPtH295wokXC__ofW0pz-szjdpvtbOqFBl7VK9LNSGHiI3yU-ws1RbcXsHIk8IcyV9_Wx4PX5i14klMbbNHqluX7egq9xeeKtzmKZKOwVHRIuXRKbwFzbACB9AL-PS5DxVuV0DyQaOOaL9HXMMv3frzq1TUMAY-CBM00SBHTwnCdAH1sEMGoVbECa1vNwTt5V1rzHV28r7k63lJJoXeAvfmGetjL6FE'
  },
  {
    id: 'neon-nights',
    title: 'Neon Nights: The Search',
    year: 2024,
    type: 'movie',
    duration: '1h 50m',
    genres: ['Action', 'Thriller', 'Noir'],
    rating: 4.7,
    description: 'A striking close-up of a human eye reflecting a rain-drenched cyberpunk skyline in electric blue and blazing crimson lights.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCS2q25QalREBmcPInnhcNLue2--63IlnnCRO4jfxkBOKS3jBD-SF1aHXpdQl7OAyY6Dze9xMb8g5UwbjYPjjrHTrBDcNvJfp4JAl2a0ldXhpj3u24VRdCmZNUIRSJt7W4bRgSLgbxyWz_q58uc6K1NPnXtwoYn-ncKmdZVfuCyVnrnIvYculHnJ74RNSzAyqkyTdrWMLyKd8J5CwjlsMH7EBJgf2iEg8aqBdpSdwDIWWA8w-N3tEhdh_m-nFYDoVKAxKsZw8_oNKk'
  },
  {
    id: 'shadow-protocol',
    title: 'Shadow Protocol',
    year: 2023,
    type: 'movie',
    duration: '2h 15m',
    genres: ['Action', 'Crime', 'Noir'],
    rating: 4.8,
    description: 'A classic silhouette of a detective in a fedora standing silently under a glowing streetlamp in a rain-slicked neon street.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJegrYmvcgj92fnxH1zC8XusjhxalX_D4BLC3mQDmlLb1yNXAzG_MZUhPl9JGqF1zVmUzjRMIJlfH0sTwcS6msm-CjjsVwTi_Ic5kPlC8FPj12Nx_QtRBPBZScuYi9I1JKk2MtRNRtQtRiqSDb3pXoGAy2Y-mXibiB3185kQ31v9zUku0gKgOL3rv3fZnL7IFXd4xhcSpXmk6wHeUim_kxrIHFPeF38wUhILgPdNqOEm3PDipyQvtT-4RqJT_0zo87PpTIGlZtSHs'
  },
  {
    id: 'the-last-nebula',
    title: 'The Last Nebula',
    year: 2024,
    type: 'tv',
    episodes: 'S1 • 10 Episodes',
    genres: ['Sci-Fi', 'Space', 'Drama'],
    rating: 4.9,
    description: 'crystalline spires spike outward under twin golden moons on a desolate desert planet bordering an glowing purple cosmic dust cloud.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBttaz4sjIUH8-C6CSJy-taLhI8zlrTA58YTnxNyBk4NWNllarSVrT8e0qixFmcgijeNa2K8tBuc4nsxqMb5Sfg6HBrWUn2FpA29BeJZ7_HkoYs3s17-J1U_4GNlPK3v5RBnPA1J5gG5_G0zAjO60_pABwJPE4gbGWDW2uIPVRlZB6TRW3cD6Drl7JrwPt4H2wM_Nr8nYt7EDOtcrpD3wAnjV5BJBGZn0Z4IAL9_acw9HZqW5xpI7R5PamRksJoXzDeZ21WcYTQ0cI'
  },
  {
    id: 'noir-chronicles',
    title: 'Noir Chronicles',
    year: 2023,
    type: 'movie',
    duration: '1h 48m',
    genres: ['Thriller', 'Noir', 'Mystery'],
    rating: 4.7,
    description: 'A projector beam cuts across a smoky obsidian screening theatre room, casting hazy shadows and creating a nostalgic cinema essence.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDz8CgHsHIwcnKbI_5BsxbV6XyM8Y8rBftiP2G2EdF3jwRe2jKwJF6ORFaTZ1euhd2YyH37O5AphcIU3Z3x6EDE5GnCdbRePGaanoBz7jYLif460D-o3nLfioyEFFwzhtvA3W-NHGs7xiD5ELSIkNStVCwMwgdlmBXrejJDHg1fTfWP5Anrbjq3Ilxm29RZNHYk4d8CKPHnFu7li6CsuTWxYU2mUvZvQ3ilVGF9InvfMWJMis3mPClOH8w5BTPcQm4qvE8wZ-cJnB8'
  },
  {
    id: 'gilded-empire',
    title: 'Gilded Empire',
    year: 2024,
    type: 'tv',
    episodes: 'S2 • 8 Episodes',
    genres: ['Drama', 'Romance'],
    rating: 4.5,
    description: 'A sea of swirling golden silk currents meets glossy black ink elements in an abstract glassmorphic and elegant visual landscape.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFQhfffSbRsdfqKRmBTk9lb-qXmkE1IvCqbVCnBy7Csaf1jcz9mYTNurK5ABhRmuL8t0deH5RNxZdsOMQuRcw_3AWl0hfaQ90GrrPxC6h_YRTnI-lKa5Tubpk-AR2jZap8rrnIyvV3UBg_duJKdYXAGoSX8CALUs2rTuVn7XQ0KP6OCMTpdzlGbq6swXsWlZd6PEPSpqdZH8P7oLfcV1pC1cWhrQpZ8dhqnKP1XllMYVuCD3f5ryLhLZfV-_0lop09uWAVh_xwdtM'
  },
  {
    id: 'binary-horizon',
    title: 'Binary Horizon',
    year: 2024,
    type: 'movie',
    duration: '2h 05m',
    genres: ['Sci-Fi', 'Cyberpunk', 'Action'],
    rating: 4.8,
    description: 'A lone figure advances across a sleek concrete bridge towards a giant glowing crimson portal set against a misty twilight skyscraper horizon.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAK2YvsRk0_mtkdr5-rNI3VdqOedjjwh2haj9LdlBdfQBNWwbTP0726gzoWvDMHcmKxwkaX1OlNHQIzKrrcRlV-4mmZK03BGQ1TUa1WxY0VuGI43CBkw-dAJE1kcOciuYyichtLzNSsHoDT4GTvODWdGMI7iQS9irrldZkF38c4fGkdZlOmDGQpqVmNKZrf5nfJdjiZa44yv2uMcoDeVSO-f-O0ShFNgHb5EBTSAEhWwDvEXvJB1brqpGutaOJe-7oYBZ6GPxuRbj8'
  },
  {
    id: 'neon-requiem',
    title: 'Neon Requiem',
    year: 2024,
    type: 'movie',
    duration: '1h 55m',
    genres: ['Action', 'Drama', 'Noir'],
    rating: 4.6,
    description: 'Rain pours over a high-stakes Tokyo street at midnight, with crimson and violet advertising signs melting together on wet, slick asphalt.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDLbeS0KHk_SwZrBXCfqM_9_HppIuI2Ajvqt4jnfQ0VgYuNdjogQ9VwLTH3y0HHEtVYhd9UQmrVVy0T3ZPAD6gXyq3pXk3LyuspnY7JF-Z7Yf8etgz3hDa9-wru7WSe9j9a9BOY826jBhhnFQhqta3OrihvrIIOZP0neFDeIES0mG-NyteyCUNTUrot-P9eY1o_p25Q6SKWlt_2PlXXicIF5G6n0hsbOXm1VtcCwLZ8kc1T8ZSadI5VvSToQcvTssfQetAnMMhttq0'
  },
  {
    id: 'the-last-drive',
    title: 'The Last Drive',
    year: 2023,
    type: 'movie',
    duration: '1h 42m',
    genres: ['Action', 'Thriller'],
    rating: 4.5,
    description: 'Streaks of ruby-red headlights blur into deep shadows as a high-speed sports car weaves through an urban night-time highway maze.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKDDlyFbyb55F7U8_0chNfAosKQtQknNQzk-gSLqOF-HssDJLYPBNGniRHr1f011JaOLjXtrjIWNnefpWG8cXJoatJo-4A-bxz_sqRFIcktGC1hZRaD65A_k52NzaTxlQF6Vi2Vx6HIwY_3TeL4RNFSaCrAR6rWM9veXh_NNIBOS_Ut5NS7gNtIdi2ZfxhSxv38_dChcWjmt4dq0Ksx11CQ8cMiDAvgkTMhYuE-ybCKjbfpoKr2DatM0Ryg1_RbPQHPIdfdU8tIXU'
  },
  {
    id: 'whispers-in-fog',
    title: 'Whispers in Fog',
    year: 2024,
    type: 'movie',
    duration: '1h 38m',
    genres: ['Horror', 'Mystery', 'Psychological'],
    rating: 4.4,
    description: 'Deep silent forest shrouded in cold emerald mist, spotlighting a single old paper lantern shining with warning gold sparks in the background.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVK9jNnIkpW4Q5Zry4RfTnlopU5hWrEvFhFfoJlKGyvrnVXGU_sAOTfj0Psh1U1Cc5wHRt5gp_79jKBhK-hMbr3-F1ZR5bGdwcboUUm41TVvmogl4Y5hvImgkLF_KFV4Z9tXQfR6wJvb6hstoN2XyKNkw6aditUo7A9kCng4tEm8vjP_qJPo9iRy3Fb7slQmvdKhYc70UqZTlTpOO77AXS1yd0dmSkWtVReDnziKWeMHF9D3VE3QOhQ2MVQ-2pqrjmWISdq23JZR4'
  },
  {
    id: 'neon-district',
    title: 'Neon District',
    year: 2023,
    type: 'tv',
    episodes: 'S1 • 12 Episodes',
    genres: ['Sci-Fi', 'Cyberpunk', 'Mystery'],
    rating: 4.6,
    description: 'A shadowy protagonist wanders an alleyway drenched in electric cyan and crimson light pools from industrial skyscrapers overhead.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBgqNITO1sJCuI9S_nsMt6oZEPoD6nc4ntJm0T8eYCzowCV3DD1Qqg4N0ryhdjv1aST4Kzm8PXcQrsRCPCvDVKc_qAY651cV2sXNSULfGz2P4heETLVl-J92RMttTce7xXaV7PonGVHJtnquUJejAU7Anw43RiBkt_750SloMzicpGJ6kSX7u-eo2gFpWwi2kZLG7sijycp8kds25MvLofm1llBB-Hn0PXn7xYVio5zdM2TRwORpZwuqzIgfM7wGSedPUQNvxYroJI'
  },
  {
    id: 'inner-space',
    title: 'Inner Space',
    year: 2024,
    type: 'movie',
    duration: '2h 12m',
    genres: ['Sci-Fi', 'Psychological', 'Arthouse'],
    rating: 4.7,
    description: 'An abstract, surreal journey showcasing a close-up human iris rotating around swirling violet constellations and crimson solar wings.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBjqmTdYJlTtR3ZnuGN7mZTXpRTA9ZOSgtk9c0gXBm15vKjoAlu6ez16o3jokfndUGgPQvBPw13ue45YI_Zi-LFQG4LrcVFRGRF1tqdc-PFmGKfjZcV-nZvpdihSZYqHjrSOPyKvMW2rjY4ehF7vm8mEDg5Ki2gSt-rL_Q76pJqU8U1Jgv3IkWvyR1NFqfZtspVS1J0RG4UuvQXOrrbs7CcGajQ1pLctBwTVpAb24VNi3kv31ozqvq5bAsWWtWMzYwvXBOMXrLlF3Q'
  },
  {
    id: 'the-red-cabin',
    title: 'The Red Cabin',
    year: 2024,
    type: 'movie',
    duration: '1h 51m',
    genres: ['Drama', 'Thriller', 'Suspense'],
    rating: 4.6,
    description: 'A desolate cabin glows from within with high-stakes warm amber lights, isolated under mountain ridges at midnight dawn.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAeTVwPqG-6aR6MVovKmHfjSRgIjXqKT_Wa_gwY15bkTOI5gTnfxc2E3ihMHXuHKeS2DEdjQAjmq-5sX6q-OfRg-xiRRqHVMiTJ1ekMWGIjjJjUBgCpLs2CvABDWXfnabCiQ8xl-V1ye5IKqRr4n219tj6R7D5ZB90Xw7symHtN0QIB5ZL_2CJEZsnZNU1bt8icnxub8xzEstFSHRpu45e-j5BR5hC0xxsRRqz8OMhWxa-hq5AL-X3NPILEguzUefLoaQ6rbwaHVRo'
  },
  {
    id: 'room-404',
    title: 'Room 404',
    year: 2024,
    type: 'movie',
    duration: '1h 54m',
    genres: ['Mystery', 'Suspense'],
    rating: 4.5,
    description: 'A symmetrical corridor of an old high-end luxury hotel illuminated with golden warm lanterns casting shadows of expectancies.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByJJ6Ifr3XmLFCoybc5xbewG_7IWmVHyn6nzyyG1ZyssrRDV5eTAKBH5o_aCJgR4ez6_PS73kc2IbBGljOJqcb4G0yjav9Ihns8YkNLmITwAxV_bDa_p2USBK-JuKsDmlDoTd4LhzIqlGRMwsv2Rz6sRYuwQpVCZYGaQ9RHuW76NQabmBXoP4iNZ4hu-fEn25XcGEdW57AlTkIznXLa-zAHYIF7j-94y_YOWWDkcBo2oEAywIb5FRNvTuH2dyww0z2XIfigcnkjt4'
  },
  {
    id: 'midnight-orbit',
    title: 'Midnight Orbit',
    year: 2023,
    type: 'movie',
    duration: '2h 00m',
    genres: ['Sci-Fi', 'Space', 'Adventure'],
    rating: 4.7,
    description: 'A single astronaut floats in state of drift inside a giant nebula characterized by crimson and gold celestial gas walls.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-W2b1pLJegTm77sMnHYDsjfiEIRucwjWTjYWIomEZrOj_nL_PEdZYUnI8yuavrp6v3oGdD7-MoL3dT6tx09XBigiPWZZbDdIh_ITeqqWTcZvchN_MZAAoc8abw34qVr3XyqTJG6SpG7wL90SWCv68sZtXAN6KTTqvAYH33WsWpQ3n40bqJ9bLzjGMGpYBd7nj0WG7A9SGQEuIu3BcRwRfha91wHalnnkQU4HE4HC9dlP55gU57k-xR1I3v-zFYjSenTqfH6g4hiI'
  },
  {
    id: 'neon-syndicate',
    title: 'Neon Syndicate',
    year: 2024,
    type: 'tv',
    episodes: 'S2 • 10 Episodes',
    genres: ['Sci-Fi', 'Cyberpunk', 'Action'],
    rating: 4.8,
    description: 'Geometric architectural lines glow with high-power red neon rods amidst towering technological blocks under falling dark rain.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6XaXLT83aBzT-10yEd1-xZXaf3RBx65S_UQ9tT4fup-UFZdQIkaA3PG0LonJ9nODDhuydYaRGndxZ5k2RcwT2Qk_mjTqO10AVF3NCJAK-vVmL9ZErZRmnoQwkzWTbwne7A_JMEL1M7SyTqry_9ueT2wiBZGfqnCEEVHEBUd5MaUJLBGYamhr9jNPYiFAIl0CN2PBmRKF5P9-DIzkUSlWc_N2GIdSGQfaCHbPGfsJWlbG8juFO9PlvVMEqs7m47QifKncYAN8IPHo'
  },
  {
    id: 'vintage-road',
    title: 'Vintage Road',
    year: 2023,
    type: 'tv',
    episodes: 'S1 • 8 Episodes',
    genres: ['Drama', 'Noir', 'Mystery'],
    rating: 4.6,
    description: 'A pristine retro cruiser car sits parked outside a dimly glowing 1950s diner bathed in warm golden ambient signs under a violet twilight sky.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuADuLLsBoMBmr1Czba30Vvi4yVviV_aLl9ohO1JpZ0AkBglTwEOSC7MSHtkMwMaWX-llU3zl5Pja4xSLEf1CO0fv-n936p7an_fSmQQnMeMqzqYXJb1dK4d74zsLTx5746RsEK0AfbqZF2NEsc--BkFe-EWSiLYEpqAUj3lUQVN5jSCS3DccgSnxmDP2l9AXSGNLNvpRQWNbK4WNoU4wJmRZc9Hff0pRM1AXDFyPqJv2BwLnqRuOs88XqKfenkUYzRxYoaCPtMTkCc'
  },
  {
    id: 'binary-pulse',
    title: 'Binary Pulse',
    year: 2022,
    type: 'movie',
    duration: '1h 52m',
    genres: ['Thriller', 'Drama', 'Technology'],
    rating: 4.6,
    description: 'Dozens of monitors glow with digital emerald charts in a security control terminal, reflecting a high-stakes investigation theme.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD89U8vGLNKKexfrGSUmc38TL3OsXjW_X6d3B5hlYGj8THvOlZP1Rqy9SKWeARGvN0Nq73LzqEiwbpS5uQ-6BzF92pLEze7RB7o_9pIRa8ET0X6TAMRcWqVlFI-AmeN-zmpR_pASiE9puccQ6xkexNngHWIew_upX5e3DnkSlODuY_QKHwLy6vLGSHNyfcKKeRDfXIQtfgsZc114PvhclhQDy8dQiA83i1faRiiICADloK6cMISxoXeG4UElBYWIiQ9ogXfkTU78fM'
  },
  {
    id: 'the-final-act',
    title: 'The Final Act',
    year: 2023,
    type: 'movie',
    duration: '1h 40m',
    genres: ['Drama', 'Mystery'],
    rating: 4.8,
    description: 'A dark, smoky theatrical stage where a single dramatic white spotlight hits an empty ruby velvet armchair on center stage.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBSmwpY9t30ygSoMYdjWM-3owK3LsBZj-PZ08foXi1SNrrHjv53wkjcNq8CPKUuwja2vVoE1R_2dT5b3vwlUK4gpcECN8zIeLT20AULReQnyojUOXhx76F-oUTlKPygupJtbKQnTgQQkcmrWl3mwCbGk_rJ9nRgh13TW9gPCqN-GwRybVTEcb3kg1u8qy7aodb6XuinkvimFMkbXNQEzX0CfQzl8-9d0ZGUKQop-byZnM5PChA7RuKSW_h_KkilbhMjhaJER4OS3lg'
  },
  {
    id: 'horizon-bound',
    title: 'Horizon Bound',
    year: 2024,
    type: 'movie',
    duration: '2h 10m',
    genres: ['Adventure', 'Drama', 'Suspense'],
    rating: 4.6,
    description: 'An airplane cruises across moonlight-sparkled oceans under smooth clouds, reflecting peaceful and grand luxury adventure scales.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDLVQXY4MpcDz0Sr5WkatY0u521DkdB2hfGDbPBEhdUBcH1K4ji_h-nx8y9TB_CAdlk9DDsRlgVCd2BjJqgrR8ghkR0NbiPTgWe0UgaSq9iZMl7Vqp4a3HZmEAwecmX5bknF14mda6WS51dG1RiZsAP7n8_NlbF3oEFythhKoBsHoE4msxtgLfICWvbCtX6Y2DB95pyr2VejREmOPGT2lSuO8o4suOL5N0BwzkdSERL2gPNobftCsKKfuS4qMqgO8wS2BDgMTdrMNs'
  },
  {
    id: 'ghost-logic',
    title: 'Ghost Logic',
    year: 2024,
    type: 'tv',
    episodes: 'S4 • 12 Episodes',
    genres: ['Sci-Fi', 'Thriller', 'Technology'],
    rating: 4.7,
    description: 'A hand reaches out to touch a shimmering digital display matrix composed of floating particles in deep darkness.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDRGWj0kPt-89i-1rFkO3S5Xr0C4_ndpuCLLGMdT4iD74ZbZS-mur4Bok_7WiDXhF4Jo9wD27gviWXiTzMLDcWBiVKDLf8wjFqQ03JS5BW3leBu_sB0UkWz-6swfKS825-ncUkKOG7tjihCN9avQRKZiKHNkLkn51Y1hOvvJCjYCyHx3BniaCF2zMy_EXZmEnpG0V4VuknBl2nDTBZrdZIJCG5Btu9oxQNFI6QBcZBN4-tt1iKtmuLOi5XI2gszgrkyh7Hz_USjZ2Y'
  },
  {
    id: 'urban-jungle-last-city',
    title: 'Urban Jungle: The Last City',
    year: 2024,
    type: 'movie',
    duration: '2h 18m',
    genres: ['Sci-Fi', 'Thriller', 'Mystery'],
    rating: 4.7,
    description: 'Green rooftop gardens contrast sleek skyscrapers in a futuristic eco-noire metropolis overlooking a soft magenta dawn horizon.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDB26vuQYA3ajM_--debBL2pqZoAg8eqtUFAEYlKwRu-pNuDH_U4XEa1ByqT8jWD-8Qu2Uc6S9KO_jIJ-H4wsRHUf_4_1Ot9-PqljEX9lls3aX-aNnGE20L_VRSm2RNiTli-GkkPZU31DUBelVR6b4VyCXt5WRmhe6TT3BZrrWXGW4Nhxea1VX5NHRqpwJTSBfy3LbbSOR-sCQ2E7N_5xQW0SlBHAudmv0SdWFKkStT6wWSTZgrqz0WxisYk-8U1WqEFO-C2RlLAc'
  },
  {
    id: 'kingdom-fall',
    title: 'Kingdom Fall',
    year: 2024,
    type: 'movie',
    duration: '2h 25m',
    genres: ['Sci-Fi', 'Cyberpunk', 'Epic'],
    rating: 4.9,
    description: 'A ruined gothic dark castle standing on jagged cliffs elements, illuminated suddenly by lightning strikes in storming navy horizons.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAWEKVUDmn6zSQRm_-2C9CvNNUwBf2yXBJbs0-dlcZVrQ-ni5zzcqvvw-0pWAPFN7BoLO8_mdUAuiienL1jzDsGNA6SV19uLqn_cr3jHSYuh-RQhv5zmywjaEE-vW5bYFMJ3XnPWdMqZwOqPsa1C8Ck7c1YRAPmMItXPY13Ey0bO8_jh8Ep6noO1ZnRsJeaanvwsWjYh4mGgXcYOn2CKzrarLXfUb-OCXIXjlte-ViZtTdB-sTT5lakr5g5CH4RMXPvndwscLKfu9Y'
  },
  {
    id: 'algorithm',
    title: 'Algorithm',
    year: 2024,
    type: 'movie',
    duration: '1h 45m',
    genres: ['Suspense', 'Mystery', 'Technology'],
    rating: 4.8,
    description: 'Swirling ribbons of cold luminescent light float through a dark crystalline matrix pool, evoking glassmorphic digital network architectures.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAp1maWCd4NqNrlpF8VG2k1DiiagAWQRzSPtbJVuPbDyxmjFT-iSKszywDRC7GpgsdblA1mqopC3UL1PXVDNFTZhdpJC7UaKpenop9bvSG-R-rmGgjVUOmJGO1ErJ8YdyUEEWG1taST8wdxoXATNhzNAAQ8e0e0dAnETLqDwCdSdrSNcur6e9pdH58RdiHMLw-LBsM8fgItRRzApZPcNMJnBwmW50BAaZfZUmedeBrvAeaNwzAuP_C3bJr7B18lUss2JQk_cKF8hJ4'
  },
  {
    id: 'the-long-goodbye',
    title: 'The Long Goodbye',
    year: 2024,
    type: 'movie',
    duration: '2h 11m',
    genres: ['Drama', 'Romance'],
    rating: 4.8,
    description: 'An emotional, highly detailed close-up portrait of an aging theater icon standing under soft warm stage spotlights in quiet shadow realms.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBVKtdfPeLzAdXF2GptP8Pd5VlQb6cnN5USMt-NuuD-uAUAX47bDHzJoTRrqxmuM4AjdgyXD9gtHtm3pcsmc0ED4AatckxEYMQZnuWOZhqxPT0LDI8XMRUMeo1K03B9_ehmqdy9EOr5nfHjbkhJJ-ClARSt6KBquFj4x0riEyHA3GmRkyeCNVlGQK4M6uWcoGPJtd1yYd1IOnE5cUGguFqQgftqVXo5T6FkWyYnTfvJS0LY0fdmtxQO52CZgrdUEnUCEMCvN_kxVT0'
  },
  {
    id: 'the-void',
    title: 'The Void',
    year: 2024,
    type: 'movie',
    duration: '2h 01m',
    genres: ['Sci-Fi', 'Arthouse', 'Mystery'],
    rating: 4.9,
    description: 'A striking minimalist poster depicting an astronaut suspended in a deep-space silent gap, backed by a crimson and gold cosmic galaxy.',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDxF4bG9Kp3jZzet3cNqtuqpc4m_F5eI9oRH-8xGQpegHTboaBDslZ_bwtBayPnTK08i0UO4brlMPWWJufArUOPUJtqS5hRfqwTQkwBZ4hbFoMbTX-Fr2sZKO7q9P8-1X32oeSg2urwcycxTZSCVCUx8d4kFBKneOdvU6c4dPI5odgWNQ4Tgiyvb620NQCrHKrsFGbAJsD0vmW3MpdFymiJXSRBnFXk55PWZ058NBN07iHjDepXbFXg1cqf0iI_mYnsyieLvJnjKcY'
  }
];
